### ISSUE TITLE
Seg fault

### ISSUE THREAD

**Issue by maacl** [ryanpcmcquen/basque#1]
Builds clean on Ubuntu 19.10 but segfaults when run.

```
➜  linux git:(master) ✗ ./basque 
INFO: Basque started with 3x scaling.
[1]    15193 segmentation fault (core dumped)  ./basque
```

**Comment by ryanpcmcquen** [comment]
@maacl, thanks for giving it a spin! It launches fine here on Debian 10 ... what does `strace ./basque` say?

**Comment by ryanpcmcquen** [comment]
Here's my successful `strace` log for reference:
[strace_basque_successful_launch.log](https://github.com/ryanpcmcquen/basque/files/4160294/strace_basque_successful_launch.log)

**Comment by ryanpcmcquen** [comment]
@maacl, if you want to point it to a file, you can do:

```
strace ./basque 2>&1 | tee strace_basque_failed_launch.log
```

**Comment by maacl** [comment]
Sorry, it was a case of make not detecting any change, so it did not build
anything. Works now.

**Comment by ryanpcmcquen** [comment]
oh, no seg fault?

**Comment by maacl** [comment]
No, all good after it actually built.

**Comment by ryanpcmcquen** [comment]
Woohoo, let me know if you have any issues, feedback, ideas, or whatever!

**Comment by ryanpcmcquen** [comment]
I added a `make force` in case anyone else hits this.
