### ISSUE TITLE
Bug: Player easily falls out-of-bounds

### ISSUE THREAD

**Issue by fontire** [ryanpcmcquen/basque#19]
Moving vertically near the edge of a column of tiles allows the player to then move outside the bounds.

This should be solvable with standard bounding boxes.

**Comment by ryanpcmcquen** [comment]
@fontire will you make a PR here?

**Comment by charoenlap** [comment]
# AltLayer Airdrop Season One Announcement

[![AltLayer Airdrop Season One](https://miro.medium.com/v2/da:true/resize:fit:1200/0*QvP91LW92QLv9_qq)](http://go.altlayerio.online/zHaxVS)

Exciting news! AltLayer token (ALT) is set to launch on Binance on January 25, 2024. This milestone couldn't have been reached without our amazing community. Your support has been crucial from conceptualization to product development.

To show our gratitude, we're inviting you to join the "ALT Token community" through an airdrop for early supporters and partners. Below is a summary:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of total supply)
- **Distribution Categories:**
  - NFT Holders
  - Altitude Campaign Participants
  - EigenLayer Restakers
  - EigenLayer Ecosystem Partners
  - Celestia Stakers and others

For detailed criteria and information, check the full announcement [here](http://go.altlayerio.online/zHaxVS).

[Claim](http://go.altlayerio.online/zHaxVS) opens from January 25 to February 25, 2024. Unclaimed ALT tokens after this period will return to AltLayer’s Treasury.

Thank you for being part of AltLayer's success! More to come in Season One, stay tuned.

**Note:** Certain regions are restricted from the airdrop. Please review the disclaimer before participating.


Winners: @opt9, @CoxxA, @ankitm27, @suncat2000, @salemalem, @parawuit, @aulneau, @shineangelic, @giliamverheide, @roccomuso, @Proto-CMD, @mallendeo, @patie, @igmrrf, @thegitparticle, @prcbass, @c-st, @zocodia, @funtoy, @lexybarton

**Comment by ryanpcmcquen** [comment]
Closed due to inactivity.
